### ISSUE TITLE
Idea for running skepticoin on gpu

### ISSUE THREAD

**Issue by kafkaphoenix** [skepticoin/skepticoin#15]
https://www.geeksforgeeks.org/running-python-script-on-gpu/

**Comment by sashimi-houdini** [comment]
Since mining is a zero-sum game, I'm not going to invest in it unless absolutely necessary. This could be e.g. when the network is overrun by people that have ostensibly cracked the GPU trick but are keeping it to themselves.

Also, the linked page does not actually show anything about running our particular PoW on GPUs, so I'm not sure how directly applicable it is.

**Comment by kafkaphoenix** [comment]
@sashimi-houdini well from previous project I did you only need to import cuda and run your function in the gpu with the helping functions from kuda, but this would only work for nvidia graphic cards but yes as you said it's not a priority just a nice to have

**Comment by kafkaphoenix** [comment]
oh and reading again your comment you are right I'm not sure how this would work with the PoW, if I find something more I will get you back cheers
