### ISSUE TITLE
How can I contribuate ?

### ISSUE THREAD

**Issue by dzGeekyGirl** [skepticoin/skepticoin#19]
Hello, firstable I don't know if It right to put it there it not really an issue
some background before we start
I am a chemical engineer from Algeria leaving in Europe and since the COVID-19 hit us I started learning more about computer science and programming I have some basic knowledge in html, css, js and php and can understand code writing in python but, never write something relevent
I want to contribute to this project. I am new to GitHub I don't know the process I read abuot git, and GitHub and some commandes like how to clone, switch between branch, push and pull .etc.., But, how can I go further please ? Any read ? Any recommandation ?
Thank you all.

**Comment by sashimi-houdini** [comment]
> I am a chemical engineer

Great, since we're in the business of turning lead into gold we could certainly use your expertise.

>  I am new to GitHub I don't know the process I read abuot git, and GitHub and some commandes like how to clone, switch between branch, push and pull .etc.., 

This is the part I can't really help you with, other than [github's own documentation](https://guides.github.com/activities/hello-world/)

_however_, our project could certainly use a good "CONTRIBUTING.md" document; I'll try to get that in order.

**Comment by dzGeekyGirl** [comment]
> Hi :) in the meanwhile you can take a look to this https://github.com/firstcontributions/first-contributions probably it's a good starting point

Thank you very much
