### ISSUE TITLE
Loading blockchain takes long

### ISSUE THREAD

**Issue by lk16** [skepticoin/skepticoin#38]
Currently the blockchain has height (depth?) of about 80k.

Loading the chain takes a while, on my machine it's half a minute.
In the future this will be significantly longer.

Some items for discussion:
* Do we need to load the entire chain?
* If we can do a partial load of the chain, can we load items from disk later?
* Do we even need the entire chain at all? (Would the last 20k blocks suffice?)

Obviously this is not a big problem now, but it will become increasingly more annoying as the chain grows.

**Comment by atramos** [comment]
The main problem is that each block is a separate file. If they could all be concatenated into a single file or written into a sqlite or even zipfile, it would load much faster.

**Comment by lk16** [comment]
Another drawback is that filesystems just get slow with a very large amount of files per directory. I don't think we've reached those levels yet, but we will get there.

Maybe we can group the JSON files per 1k or 10k or so into a tar.gz or zip or similar. I'd like to stay away from sqlite, because when my PR #35 is merged, there is only one thread/process touching the chain at the time, at least for mining.

That way we have some middle ground between having one huge zip and having a ton of small files as we do now. This would require a bunch of refactoring of the code touching the chain, which may be a good thing.

@sashimi-houdini opinions?

**Comment by atramos** [comment]
Please review PR#43, it makes 3x to 20x faster loading depending on whether you compare pre-warmed or cold-started.

**Comment by sashimi-houdini** [comment]
> Do we need to load the entire chain?

Basically, yes. I suppose we could offer "pruned chains" as an option, but only as an extra option, not as the default, and at extra development work for (for now) very little gain, so that's not a road I'm inclined to take.

The bigger point is actually this: currently, the whole blockchain and all its derived information is kept in-memory in the `Coinstate` object. This is an approach that will not scale sufficiently in time. Once those datastructures are moved to a "disk first" approach, the whole idea of loading the blockchain from disk at each program invocation will disappear. That's for another issue and another day though.

**Comment by lk16** [comment]
Not sure if mentioned on this issue, but I have a branch (without PR) for compressing the chain on disk, so it loads a bit faster and uses a lot less diskspace. This is a WIP, so I have no numbers.

**Comment by atramos** [comment]
I did take some measurements and found the compression is around 3:1, but timings are about the same.
