### ISSUE TITLE
Feature Request: ERC20-style tokens, Non-Fungible Tokens (NFT), and Smart Contracts

### ISSUE THREAD

**Issue by refacktor** [skepticoin/skepticoin#58]
I'm grouping these together because I believe they can be built more easily from a holistic vision than individually.

**ERC20-style tokens**

These are essentially a cryptocurrency-within-a-cryptocurrency. This could be supported by making just a few small changes:

- adding a "create sub-currency token" transaction type that lets you set parameters (currency name, symbol, project URL, maximum tokens, inflation, sub-units, initial owners), 
- adding a "currency type identifier" field to transaction blocks, where "SKEPTI" as the default type can just be 0, while the other types are a hash reference to the previous "create sub-currency token" transaction
- modifying the balance calculations so that each sub-currency token is added up separately. 

The Ethereum implementation of this is far more complicated, because that's a specialization within a generalization, but the end-result is the same.

**NFTs (Non-Fungible Tokens)** 

I'm willing to be educated on this one, but as I understand it, it's just an instantiation of a "sub-currency token" as above but with a maximum tokens of 1, a sub-divisible unit of 1 (i.e. not divisible), inflation of 0%, and an additional field for "digital asset representation". The asset representation should be split into multiple blocks to ensure the mining difficulty goes up with asset size.

**Smart Contracts**

The key enabler to smart contracts is the ability to have miners be willing to execute code submitted in a transaction block. The challenge is how to run untrusted code. You need a sandbox. Ethereum took the approach of creating their own VM (that's the sandbox) and a special language to run on it. 

I propose a simplified approach:
- our language is Python, 
- our sandbox is a Docker Container with heavily restricted external resource access,
- the contract source code is an NFT (see above)

With this in mind, we only need a few small changes in order to support Smart Contracts in the Skepticoin Blockchain:

- Ability to create a contract and have its source code stored on the blockchain: the source code is an NFT (see above).
- Add a new transaction type, "execute contract". 
- Miners will decide to include or skip "execute contract" transactions based on the mining reward offered. This can be a simple configuration or a mining operator can manually review and whitelist the available contracts. 
- When a miner decides to mine an "execute contract" block, the miner fires up a Docker Container with the blockchain on it and invokes the contract source code, waits for the contract code to generate the finalized block, then mines that block normally. 
- If the contract code blows up or times out, miners can blacklist it, and the "execute contract" transaction just gets discarded.

I'm still a little unclear on what prevents a miner from just "fake executing" the contract.

**Comment by sashimi-houdini** [comment]
The lack of any more advanced layers of bullshit is [actually quite intentional](https://github.com/skepticoin/skepticoin/blob/master/docs/design.md), so I'm not too inclined to go this route (that's even besides the fact that this would require some work to implement). Let's go after Bitcoin first, and see if the more advanced layers of bullshit collapse on themselves if we remove the root of the evil and (still) leader of the pack.

Re NFTs, I did think about that a bit, and I think we can even fit it in the existing consensus algorithm.

Remember that bitcoin and skepticoin are already non-fungable: each "coin" is either the result of mining, or it is explicitly tied to another transaction's output. That is: not all coins are the same. (This implementation detail has the remarkable property that it makes skepticoin barely useful, even for its main use-case: that of criminal activity. But that's besides the point here)

For the case of NFTs it's quite useful actually: we could simply do the following:

1. make it easier (in the UI) to "mint" NFTs while mining. There's 200 bytes of random data reserved in each block, which is easily enough for a url, or some funny text.
2. define how the "ownership" of NFTs is transferred through transactions. (This is needed because a single transaction may have multiple inputs and outputs, each of different sizes. Finally, the outputs may be less in total than the inputs, where the difference is available for the miner as a transaction fee. But what does this mean for the transfer of ownership of the NFTs?). I propose the following simple definition: the ownership is transferred in a way that respects the order of inputs and outputs. Note that a single NFT can be split accoring to this definition into 1-sashimi sized parts at the smallest. (The NFT starts out under a single 10-SKEPTI ownership)
3. allow for inspecting of the result (in the UI) of the above. I.e. 'show-nfts', which shows for coins (or fractions) that have the "NFT" property that you have them and how much SKEPTI is tied to each

**Comment by atramos** [comment]
> There's 200 bytes of random data reserved in each block

Where in the code is this? Is it 200 bytes per Block or per Transaction?

**Comment by atramos** [comment]
> a single transaction may have multiple inputs

This is the important distinction. Putting the "N" in NFTs would require that you never combine the output representing the NFT with another input. That is the very definition of "funging" (?) if there is one. I suppose recombining pieces of the same NFT after splitting should be fine... that's just transacting on the shared ownership of the single asset.

**Comment by PiecePaperCode** [comment]
could ANTLR be used to create a subset of python, that could run arbritary code?

ANTLR is a grammer validator. usualy for creating own languages. define a grammar where it forbits eval exec ...

**Comment by sashimi-houdini** [comment]
> Where in the code is this? 

* https://github.com/skepticoin/skepticoin/blob/3809da627c443014c17f793a4e2165411e2b4f7e/skepticoin/params.py#L17
* https://github.com/skepticoin/skepticoin/blob/3809da627c443014c17f793a4e2165411e2b4f7e/skepticoin/signing.py#L122

> Is it 200 bytes per Block or per Transaction?

Per Coinbase transaction which is to say per block

**Comment by sashimi-houdini** [comment]
I'm going to close this umbrella issue as per my remark above "more advanced layers of bullshit" and for the simple reason that it's an umbrella issue. If someone is actually going to work on a particular of the suggested approaches they can always reopen a new issue (assuming that it's within the design goals).
