### ISSUE TITLE
scalability bug: inactive peers are never purged

### ISSUE THREAD

**Issue by atramos** [skepticoin/skepticoin#71]
Inactive peers are never purged from peers.json. They should be purged or at least de-prioritized, i.e., connection attempts from the local peer to an inactive peer should be made infrequently, and eventually dropped.

This issue a subset of #31 and is possibly exacerbating #36 and #45.

**Comment by lk16** [comment]
Maybe we can add a value "last time connected" timestamp to each peer in peers.json to keep track of this?
For nodes from the downloaded peer lists, we would have a special value.

Not sure if this next part deserves its own ticket. We currently only download the peer lists if there is no peers.json. I think we could do this every time on miner/balance/... startup. We can just merge the known and newly-found lists.

**Comment by atramos** [comment]
> For nodes from the downloaded peer lists, we would have a special value.

No need for special value. It would be nice to know the freshness of the initial lists. 

> "last time connected"

Also, last time data received, and last time connection result.

**Comment by lk16** [comment]
> No need for special value. It would be nice to know the freshness of the initial lists.

That requires modification of the lists we download, which probably breaks backwards compatibility.
Since we likely are breaking backwards compatibility anyway, we should use this opportunity to be forwards compatible:
we should probably have a JSON object/dict instead of an array/list (used as tuple) for each peer. That way we can name the fields for each peer, which is also easier to read/maintain.

> Also, last time data received, and last time connection result.

I see you're way ahead of me. I tried to understand the peer code yesterday, but I had a hard time. 
Looks like you're the best candidate to implement this stuff.

**Comment by atramos** [comment]
I'm doing some work on this. I think I'll have some major fixes soo.

**Comment by atramos** [comment]
This is really a bug, as it caused phantom scalability issues ... the limit of 64 selectors on windows or 512 file descriptor on Linux is not even closed to being reached, but was breached due to ghost connections to hundreds of old IP addresses.
